name: Jarvis Voice Assistant
version: "1.0.13"
slug: jarvis
description: AI voice assistant for Home Assistant
url: https://github.com/nerevar48/jarvis-addon
arch:
  - aarch64   # Raspberry Pi 4/5
  - amd64
startup: application
boot: auto
ports:
  8887/tcp: 8887   # ESP WebSocket
map:
  - data:rw
  - share:rw
init: false
# Вот что появится в вкладке Configuration:
options:
  openai_key: ""
  ha_token: ""
  openai_model: "gpt-realtime-mini"
  speaker_gain: 1.5
  mic_gain: 1.5
  log_enabled: false
  inactivity_timeout: 4
  wake_words:
    - "джарвис"
    - "жарвис"
    - "слушай жарвис"
    - "эй жарвис"
    - "эй джарвис"
    - "цифровой ра"
    - "эй ты"
    - "эйты"
    - "ейты"
  stop_words:
    - "стоп"
    - "хватит"
    - "хвати"
    - "останови"

schema:
  openai_key: str
  ha_token: str
  openai_model: list(gpt-realtime|gpt-realtime-mini)
  speaker_gain: float(0.5,5.0)
  mic_gain: float(0.5,5.0)
  inactivity_timeout: int(3,30)
  log_enabled: bool
  wake_words:
    - str
  stop_words:
    - str